import { fileURLToPath } from "node:url"
import { join } from "node:path"
import { ESLint } from "eslint"
import ts from "typescript"
import { describe, expect, it } from "vitest"
import { compile, emitEntityTypes } from "simetra/compiler"
import {
  attribute,
  catalog,
  customTable,
  document,
  metaFiles,
  organization,
  project,
  salesDocument,
  scopedProject,
  uuid,
} from "./helpers"

const PACKAGE_ROOT = fileURLToPath(new URL("../../../", import.meta.url))

async function emit(entries: Record<string, unknown>): Promise<string> {
  const result = await compile(metaFiles(entries))
  expect(result.diagnostics).toEqual([])
  return emitEntityTypes(result.model!)
}

/** Тіло простору імен виходу: від `export declare namespace` до його `}`. */
function namespaceOf(code: string, name: string): string {
  const match = new RegExp(
    `export declare namespace ${name} \\{\\n[\\s\\S]*?\\n\\}`
  ).exec(code)
  expect(match, `namespace ${name}`).not.toBeNull()
  return match![0]
}

/**
 * Фрагмент виходу: один інтерфейс (`Catalogs.Item`) разом з його JSDoc, без
 * відступу простору імен — так знімки читаються як звичайний код.
 */
function block(code: string, path: string): string {
  const [namespace, name] = path.split(".") as [string, string]
  // Без рядків `export declare namespace … {` і `}`: інакше шапка склеїться
  // з першим інтерфейсом.
  const found = namespaceOf(code, namespace)
    .split("\n")
    .slice(1, -1)
    .join("\n")
    .split("\n\n")
    .find((b) => b.includes(`export interface ${name} {`))
  expect(found, `interface ${path}`).toBeDefined()
  return found!
    .split("\n")
    .map((line) => line.replace(/^ {2}/, ""))
    .join("\n")
    .trim()
}

/** Споживач без прив'язки до видів: у фікстурі може не бути довідників. */
const ANY_CONSUMER = [
  'import type * as Entities from "./entities"',
  "export type Shared = Entities.Json",
].join("\n")

/** Споживач з контракту: простір імен довідників і узагальнений аліас. */
const CATALOG_CONSUMER = [
  'import type { Catalogs } from "./entities"',
  "type UseModule<T> = T",
  "export type X = UseModule<Catalogs.Item>",
].join("\n")

/**
 * Перевірка типів згенерованого `.d.ts` разом із тестовим споживачем у
 * пам'яті: суворі прапорці споживача (isolatedModules, verbatimModuleSyntax),
 * реальний lib. Заглушка споживача живе лише тут.
 */
function diagnosticsOf(code: string, consumer = ANY_CONSUMER): string[] {
  const files = new Map([
    ["/virtual/entities.d.ts", code],
    ["/virtual/consumer.ts", consumer],
  ])
  const options: ts.CompilerOptions = {
    strict: true,
    noEmit: true,
    isolatedModules: true,
    verbatimModuleSyntax: true,
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    types: [],
  }
  const host = ts.createCompilerHost(options)
  const { getSourceFile, fileExists, readFile } = host
  host.getSourceFile = (name, languageVersion, ...rest) =>
    files.has(name)
      ? ts.createSourceFile(name, files.get(name)!, languageVersion)
      : getSourceFile.call(host, name, languageVersion, ...rest)
  host.fileExists = (name) => files.has(name) || fileExists.call(host, name)
  // Без цього розв'язання модуля не бачить віртуальної теки.
  host.directoryExists = () => true
  host.readFile = (name) => files.get(name) ?? readFile.call(host, name)
  const program = ts.createProgram(["/virtual/consumer.ts"], options, host)
  return ts
    .getPreEmitDiagnostics(program)
    .map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"))
}

describe("emitEntityTypes", () => {
  it("catalog interface with standard attributes and jsdoc", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "catalogs/Item/Item.meta.json": catalog("Item", {
        title: { uk: "Номенклатура", en: "Item" },
        description: { uk: "Товари й послуги" },
        attributes: [
          attribute("sku", {
            type: "String",
            length: 20,
            required: true,
            title: { uk: "Артикул" },
          }),
          attribute("note", { type: "Text" }),
        ],
      }),
    })
    expect(code.startsWith("// Generated by simetra — do not edit\n")).toBe(
      true
    )
    expect(code).toContain("export declare namespace Catalogs {")
    expect(code).toContain("export type Json = ")
    expect(code).not.toMatch(/eslint/)
    expect(diagnosticsOf(code, CATALOG_CONSUMER)).toEqual([])
    expect(block(code, "Catalogs.Item")).toMatchInlineSnapshot(`
      "/**
       * Item
       *
       * Товари й послуги
       */
      export interface Item {
        /** Reference */
        ref: string
        /** Code */
        code: string | null
        /** Description */
        description: string | null
        /** Deletion mark */
        deletionMark: boolean
        /** Predefined name */
        predefinedName: string | null
        /** Version */
        version: string
        /** Created at */
        createdAt: string
        /** Updated at */
        updatedAt: string
        /** Артикул */
        sku: string
        note: string | null
      }"
    `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("numeric and bigint are strings", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "catalogs/Item/Item.meta.json": catalog("Item", {
        attributes: [
          attribute("price", { type: "Numeric", precision: 15, scale: 2 }),
          attribute("big", { type: "BigInt", required: true }),
          attribute("count", { type: "Integer", required: true }),
          attribute("payload", { type: "Json" }),
        ],
      }),
    })
    expect(block(code, "Catalogs.Item")).toMatchInlineSnapshot(`
      "export interface Item {
        /** Reference */
        ref: string
        /** Code */
        code: string | null
        /** Description */
        description: string | null
        /** Deletion mark */
        deletionMark: boolean
        /** Predefined name */
        predefinedName: string | null
        /** Version */
        version: string
        /** Created at */
        createdAt: string
        /** Updated at */
        updatedAt: string
        price: string | null
        big: string
        count: number
        payload: Json | null
      }"
    `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("enumeration reference is a union of logical names", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "enumerations/Status/Status.meta.json": {
        id: uuid(1),
        kind: "Enumeration",
        name: "Status",
        physicalName: "status",
        values: [
          { id: uuid(2), name: "Draft", physicalName: "draft" },
          { id: uuid(3), name: "Done", physicalName: "done" },
        ],
      },
      "catalogs/Task/Task.meta.json": catalog("Task", {
        attributes: [
          attribute("status", {
            type: "Ref",
            ref: { kind: "Enumeration", name: "Status" },
            required: true,
          }),
          attribute("history", {
            type: "Ref",
            ref: { kind: "Enumeration", name: "Status" },
            array: true,
          }),
          attribute("related", {
            type: "Ref",
            allowedTypes: [
              { kind: "Catalog", name: "Task" },
              { kind: "Catalog", name: "Item" },
            ],
          }),
        ],
      }),
      "catalogs/Item/Item.meta.json": catalog("Item"),
    })
    expect(code).not.toContain("interface Status")
    expect(block(code, "Catalogs.Task")).toMatchInlineSnapshot(`
      "export interface Task {
        /** Reference */
        ref: string
        /** Code */
        code: string | null
        /** Description */
        description: string | null
        /** Deletion mark */
        deletionMark: boolean
        /** Predefined name */
        predefinedName: string | null
        /** Version */
        version: string
        /** Created at */
        createdAt: string
        /** Updated at */
        updatedAt: string
        status: "Draft" | "Done"
        history: ("Draft" | "Done")[] | null
        related: { type: "Catalog.Task" | "Catalog.Item"; id: string } | null
      }"
    `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("tabular section interface and array field", async () => {
    const code = await emit({
      "project.meta.json": project(),
      ...salesDocument(),
    })
    expect(block(code, "Documents.Sale")).toMatchInlineSnapshot(`
      "export interface Sale {
        /** Reference */
        ref: string
        /** Number */
        number: string | null
        /** Date */
        date: string
        /** Number period */
        readonly numberPeriod: string
        /** Posted */
        posted: boolean
        /** Deletion mark */
        deletionMark: boolean
        /** Version */
        version: string
        /** Created at */
        createdAt: string
        /** Updated at */
        updatedAt: string
        goods: SaleGoods[]
      }"
    `)
    expect(block(code, "Documents.SaleGoods")).toMatchInlineSnapshot(`
      "export interface SaleGoods {
        /** Reference */
        ref: string
        /** Owning object */
        parent: string
        /** Line number */
        lineNumber: number
        item: string | null
        qty: string | null
        amount: string | null
      }"
    `)
    // Регістр: рухи є, похідних таблиць підсумків і оборотів немає.
    expect(block(code, "AccumulationRegisters.Stock")).toMatchInlineSnapshot(`
      "export interface Stock {
        /** Period */
        period: string
        /** Recorder */
        recorder: { type: "Document.Sale"; id: string }
        /** Line number */
        lineNumber: number
        /** Active */
        active: boolean
        /** Movement type */
        movementType: string
        item: string | null
        qty: string
      }"
    `)
    expect(code).not.toMatch(/Totals|Turnovers/)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("required document attribute is nullable and generated column is readonly", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "documents/Invoice/Invoice.meta.json": document("Invoice", {
        numberPeriodicity: "Month",
        attributes: [
          attribute("customer", { type: "String", length: 10, required: true }),
        ],
      }),
    })
    expect(block(code, "Documents.Invoice")).toMatchInlineSnapshot(`
      "export interface Invoice {
        /** Reference */
        ref: string
        /** Number */
        number: string | null
        /** Date */
        date: string
        /** Number period */
        readonly numberPeriod: string
        /** Posted */
        posted: boolean
        /** Deletion mark */
        deletionMark: boolean
        /** Version */
        version: string
        /** Created at */
        createdAt: string
        /** Updated at */
        updatedAt: string
        customer: string | null
      }"
    `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("section standard overrides feed the section interface jsdoc", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "catalogs/Item/Item.meta.json": catalog("Item", {
        tabularSections: [
          {
            id: uuid(801),
            name: "rows",
            physicalName: "rows",
            standardAttributeOverrides: {
              lineNumber: { description: { en: "Starts at one" } },
            },
          },
        ],
      }),
    })
    expect(block(code, "Catalogs.ItemRows")).toContain(
      "   * Line number\n   *\n   * Starts at one"
    )
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("snake_case project uses snake_case fields", async () => {
    const code = await emit({
      "project.meta.json": project({ naming: { attributeCase: "snake_case" } }),
      "catalogs/Item/Item.meta.json": catalog("Item", {
        attributes: [attribute("unit_price", { type: "Integer" })],
      }),
    })
    expect(block(code, "Catalogs.Item")).toMatchInlineSnapshot(`
      "export interface Item {
        /** Reference */
        ref: string
        /** Code */
        code: string | null
        /** Description */
        description: string | null
        /** Deletion mark */
        deletion_mark: boolean
        /** Predefined name */
        predefined_name: string | null
        /** Version */
        version: string
        /** Created at */
        created_at: string
        /** Updated at */
        updated_at: string
        unit_price: number | null
      }"
    `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("scoped object has scope field", async () => {
    const code = await emit({
      "project.meta.json": scopedProject(),
      "catalogs/Organization/Organization.meta.json": organization(),
      "catalogs/Item/Item.meta.json": catalog("Item", { scope: "org" }),
    })
    expect(block(code, "Catalogs.Item")).toMatchInlineSnapshot(`
      "export interface Item {
        /** Reference */
        ref: string
        /** Value of the \`org\` scope kind. */
        org: string
        /** Code */
        code: string | null
        /** Description */
        description: string | null
        /** Deletion mark */
        deletionMark: boolean
        /** Predefined name */
        predefinedName: string | null
        /** Version */
        version: string
        /** Created at */
        createdAt: string
        /** Updated at */
        updatedAt: string
      }"
    `)
    // Корінь скоуп-колонки не має: його скоуп — власний ключ.
    expect(block(code, "Catalogs.Organization")).not.toContain("  org:")
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("custom table maps pg enum, raw and nullable columns", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "pg-enums/Mood/Mood.meta.json": {
        id: uuid(1),
        kind: "PgEnum",
        name: "Mood",
        physicalName: "mood",
        values: ["happy", "sad"],
      },
      "custom-tables/Log/Log.meta.json": customTable("Log", {
        scope: "none",
        columns: [
          {
            id: uuid(10),
            name: "id",
            physicalName: "id",
            type: "UUID",
            notNull: true,
          },
          {
            id: uuid(11),
            name: "mood",
            physicalName: "mood",
            type: "PgEnum",
            enum: { kind: "PgEnum", name: "Mood" },
          },
          {
            id: uuid(12),
            name: "blob",
            physicalName: "blob",
            type: "Raw",
            pgType: "tsvector",
          },
        ],
      }),
    })
    expect(block(code, "CustomTables.Log")).toMatchInlineSnapshot(`
      "export interface Log {
        id: string
        mood: "happy" | "sad" | null
        blob: unknown
      }"
    `)
    expect(code).not.toContain("interface Mood")
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("same logical name in two kinds lives in two namespaces", async () => {
    const entries = {
      "project.meta.json": project(),
      "catalogs/Item/Item.meta.json": catalog("Item"),
      "documents/Item/Item.meta.json": document("Item", {
        physicalName: "item_doc",
      }),
    }
    const code = await emit(entries)
    expect(namespaceOf(code, "Catalogs")).toContain("export interface Item {")
    expect(namespaceOf(code, "Documents")).toContain("export interface Item {")
    expect(
      diagnosticsOf(
        code,
        [
          'import type { Catalogs, Documents } from "./entities"',
          "export type A = Catalogs.Item",
          "export type B = Documents.Item",
        ].join("\n")
      )
    ).toEqual([])

    // Новий об'єкт не перейменовує й не зсуває чужі інтерфейси.
    const more = await emit({
      ...entries,
      "catalogs/Another/Another.meta.json": catalog("Another"),
    })
    expect(block(more, "Catalogs.Item")).toBe(block(code, "Catalogs.Item"))
    expect(namespaceOf(more, "Documents")).toBe(namespaceOf(code, "Documents"))
    const names = (text: string) =>
      [...text.matchAll(/export interface (\w+)/g)].map((m) => m[1])
    expect(names(namespaceOf(more, "Catalogs"))).toEqual(["Another", "Item"])
  })

  it("constant exposes only its value", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "constants/Rate/Rate.meta.json": {
        id: uuid(901),
        kind: "Constant",
        name: "Rate",
        physicalName: "rate",
        type: "Numeric",
        precision: 9,
        scale: 4,
        title: { en: "Default rate" },
      },
    })
    expect(block(code, "Constants.Rate")).toMatchInlineSnapshot(`
      "/** Default rate */
      export interface Rate {
        /** Value */
        value: string | null
      }"
    `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("degenerate information register hides its singleton key", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "information-registers/Settings/Settings.meta.json": {
        id: uuid(902),
        kind: "InformationRegister",
        name: "Settings",
        physicalName: "settings",
        resources: [attribute("capacity", { type: "Integer", required: true })],
      },
    })
    expect(block(code, "InformationRegisters.Settings")).toMatchInlineSnapshot(`
      "export interface Settings {
        capacity: number
      }"
    `)
    expect(code).not.toContain("singleton")
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("polymorphic ref array keeps the element shape", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "catalogs/Item/Item.meta.json": catalog("Item"),
      "catalogs/Link/Link.meta.json": catalog("Link", {
        attributes: [
          attribute("targets", {
            type: "Ref",
            array: true,
            allowedTypes: [
              { kind: "Catalog", name: "Item" },
              { kind: "Catalog", name: "Link" },
            ],
          }),
        ],
      }),
    })
    expect(block(code, "Catalogs.Link")).toContain(
      'targets: ({ type: "Catalog.Item" | "Catalog.Link"; id: string })[] | null'
    )
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("comment terminator in a title or description is escaped", async () => {
    const code = await emit({
      "project.meta.json": project(),
      "catalogs/Item/Item.meta.json": catalog("Item", {
        title: { en: "Item */ evil" },
        description: { en: "line one\nline */ two" },
        attributes: [
          attribute("note", { type: "Text", title: { en: "a */ b" } }),
        ],
      }),
    })
    expect(block(code, "Catalogs.Item").split("\n").slice(0, 5))
      .toMatchInlineSnapshot(`
        [
          "/**",
          " * Item *\\/ evil",
          " *",
          " * line one",
          " * line *\\/ two",
        ]
      `)
    expect(diagnosticsOf(code)).toEqual([])
  })

  it("generated declarations pass the repo lint without directives", async () => {
    const code = await emit({
      "project.meta.json": project(),
      ...salesDocument(),
    })
    const eslint = new ESLint({ cwd: PACKAGE_ROOT })
    const [result] = await eslint.lintText(code, {
      filePath: join(PACKAGE_ROOT, "src", "entities.d.ts"),
    })
    expect(result!.messages).toEqual([])
  })

  it("deterministic", async () => {
    const entries = {
      "project.meta.json": project(),
      ...salesDocument(),
    }
    const reversed = Object.fromEntries(Object.entries(entries).reverse())
    expect(await emit(reversed)).toBe(await emit(entries))
  })
})
