import {
  KIND_REGISTRY,
  standardLogicalName,
  type LocalizedString,
  type LogicalType,
  type MetadataRef,
  type PhysicalColumn,
  type PhysicalTable,
  type StandardColumnDef,
  type TabularSection,
} from "simetra/model"
import type { CompiledModel } from "./compile"
import { compareStrings } from "./diagnostics"
import { registerSingletonOf, standardTargetRefs } from "./stages/model"

/**
 * Типи значення колонки: логічні плюс дві форми `CustomTable`. Закритий
 * перелік, щоб відображення в TS було вичерпним на етапі компіляції, а не
 * мовчазним запасним варіантом.
 */
type SourceType = LogicalType | "PgEnum" | "Raw"

/** Тип значення, спільний для реквізиту, константи й колонки `CustomTable`. */
interface ValueSource {
  type: SourceType
  ref?: MetadataRef
  allowedTypes?: MetadataRef[]
  array?: boolean
  enum?: MetadataRef
  title?: LocalizedString
  description?: LocalizedString
}

/** Елемент з ідентичністю: реквізит, вимір, ресурс чи колонка `CustomTable`. */
interface ElementSource extends ValueSource {
  id?: string
  name: string
}

/** Джерело поля колонки: логічний опис або `{ raw }` стандартного реквізиту. */
type Source = ValueSource | { raw: string }

// Спека §8.5. Record за повним переліком логічних типів: новий тип без рядка
// тут не збереться.
const TS_OF_LOGICAL: Record<LogicalType, string> = {
  UUID: "string",
  Ref: "string",
  String: "string",
  Text: "string",
  Date: "string",
  DateTime: "string",
  Bytes: "string",
  Integer: "number",
  SmallInt: "number",
  // BigInt і Numeric не вміщуються в number без втрати точності.
  BigInt: "string",
  Numeric: "string",
  Boolean: "boolean",
  // Через псевдонім `Json_`: голе `Json` у просторі імен може затінити
  // однойменний об'єкт.
  Json: "Json_",
}

const HEADER = "// Generated by simetra — do not edit"

const JSON_TYPE =
  "export type Json = string | number | boolean | null | Json[] | { [key: string]: Json }"

/** Відступ одного рівня вкладеності. */
const STEP = "  "

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/**
 * Логічні TS-типи сутностей (спека §8.5) — вміст файлу оголошень `.d.ts`:
 * простір імен на кожен вид з таблицею (`Catalogs`, `Documents`, …), у ньому
 * інтерфейс на кожен об'єкт і кожну ТЧ. Простір імен знімає зіткнення
 * однакових логічних імен у різних видів, тож жодного перейменування
 * «першому — ім'я, іншим — префікс» немає: ім'я стабільне, поки його не
 * змінено в метаданих. Нуллабельність і генерованість беруться з фізичного
 * знімка, а не виводяться наново, тож тип не розійдеться з DDL. Порядок —
 * порядок реєстру видів, у просторі імен — за логічним іменем, тож додання
 * об'єкта не зсуває чужі інтерфейси.
 */
export function emitEntityTypes(model: CompiledModel): string {
  const style = model.project.naming.attributeCase

  const byRef = new Map(
    model.objects.map((object) => [`${object.kind}.${object.name}`, object])
  )
  const lookup = (ref: MetadataRef) => byRef.get(`${ref.kind}.${ref.name}`)
  const scopeNames = new Map(model.scopeKinds.map((k) => [k.id, k.name]))

  /**
   * Псевдоніми верхнього рівня `<Простір>_<Об'єкт>_<ТЧ>` і `Json_`. Усередині
   * просторів імен кожне посилання на тип іде лише через них: голе
   * `Documents.Sale.Goods` чи `Json` затінив би об'єкт із такою назвою
   * (довідник `Documents`, довідник `Json`), а TS не дає за це діагностики —
   * лише мовчки інший тип. Затінити псевдонім може лише простір імен або
   * ім'я об'єкта, а імена об'єктів — PascalCase без підкреслень (логічні
   * імена реквізитів підкреслення мають, але вони не оголошують типів).
   * Псевдоніми не експортуються (`export {}` в кінці файлу), тож публічний
   * контракт — лише `Json` і простори імен.
   */
  const aliases = new Map<string, string>()

  const refName = (ref: MetadataRef) =>
    JSON.stringify(`${ref.kind}.${ref.name}`)

  /**
   * Union значень перерахування; ціль з таблицею — ключ `string`. Невідома
   * ціль на моделі без помилок недосяжна (її відсікає стадія зв'язків), тож
   * `string` там — безпечний запас, а не прихована поведінка.
   */
  const refType = (ref: MetadataRef): string => {
    const target = lookup(ref)
    if (target === undefined) return "string"
    if (KIND_REGISTRY[target.kind].materializes === "table") return "string"
    const values = ((target.data as { values?: unknown[] }).values ?? []).map(
      (value) =>
        typeof value === "string" ? value : (value as { name: string }).name
    )
    return values.length === 0
      ? "never"
      : values.map((v) => JSON.stringify(v)).join(" | ")
  }

  const valueType = (
    source: Source,
    targets: readonly MetadataRef[] | undefined,
    paired: boolean
  ): { ts: string; nullable: boolean } => {
    // Сирий тип PG не має логічного відповідника: `unknown` — свідоме
    // рішення, а `null` у ньому вже міститься.
    if ("raw" in source || source.type === "Raw") {
      return { ts: "unknown", nullable: false }
    }
    let ts: string
    if (source.type === "PgEnum") {
      ts = source.enum === undefined ? "string" : refType(source.enum)
    } else if (paired) {
      const types = (targets ?? source.allowedTypes ?? []).map(refName)
      ts = `{ type: ${types.length === 0 ? "never" : types.join(" | ")}; id: string }`
    } else if (source.type === "Ref" && source.ref !== undefined) {
      ts = refType(source.ref)
    } else {
      ts = TS_OF_LOGICAL[source.type]
      if (source.type === "Json") aliases.set("Json_", "Json")
    }
    if (source.array === true) {
      ts = /[|{]/.test(ts) ? `(${ts})[]` : `${ts}[]`
    }
    return { ts, nullable: true }
  }

  const doc = (
    indent: string,
    title: LocalizedString | undefined,
    description: LocalizedString | undefined
  ): string[] => {
    const lines = [pick(title), pick(description)]
      .filter((text): text is string => text !== undefined)
      // `*/` у тексті закрив би коментар достроково.
      .flatMap((text, index) => [
        ...(index > 0 ? [""] : []),
        ...text.replaceAll("*/", "*\\/").split("\n"),
      ])
    if (lines.length === 0) return []
    if (lines.length === 1) return [`${indent}/** ${lines[0]} */`]
    return [
      `${indent}/**`,
      ...lines.map((line) =>
        line === "" ? `${indent} *` : `${indent} * ${line}`
      ),
      `${indent} */`,
    ]
  }

  const emitFields = (
    table: PhysicalTable,
    standard: ReadonlyMap<string, StandardColumnDef>,
    elements: ReadonlyMap<string, ElementSource>,
    targetsOf: (def: StandardColumnDef) => readonly MetadataRef[],
    overrides: ReadonlyMap<
      string,
      { title?: LocalizedString; description?: LocalizedString }
    >,
    member: string
  ): string[] => {
    const lines: string[] = []
    const keyOf = (column: PhysicalColumn) => JSON.stringify(column.origin)
    table.columns.forEach((column, index) => {
      const key = keyOf(column)
      // Поліморфне поле — пара колонок з одним походженням; поле одне.
      if (index > 0 && keyOf(table.columns[index - 1]!) === key) return
      const paired =
        index + 1 < table.columns.length &&
        keyOf(table.columns[index + 1]!) === key
      const { standard: standardName, elementId, scopeKindId } = column.origin

      let name: string
      let source: Source
      let targets: readonly MetadataRef[] | undefined
      let title: LocalizedString | undefined
      let description: LocalizedString | undefined
      const def =
        standardName === undefined ? undefined : standard.get(standardName)
      const element =
        elementId === undefined ? undefined : elements.get(elementId)
      if (def !== undefined) {
        // Ключ-одинак — службовий ключ рядка-одинака (завжди `true`, значення
        // дає DEFAULT): у скоупленій формі його немає взагалі, тож і в
        // логічному типі він не відкривається.
        if (def.singleton === true) return
        name = standardName!
        source = def.type
        targets = def.ref === undefined ? undefined : targetsOf(def)
        const override = overrides.get(def.logicalName)
        title = override?.title ?? def.title
        description = override?.description
      } else if (element !== undefined) {
        name = element.name
        source = element
        title = element.title
        description = element.description
      } else if (scopeKindId !== undefined) {
        // Носій скоупу: логічне ім'я — ім'я виду, тип — ключ кореня. Ім'я
        // виду з моделі без помилок завжди знайдеться; фізичне ім'я лише
        // страхує від напівмоделі.
        const kind = scopeNames.get(scopeKindId) ?? column.name
        name = kind
        source = { type: "UUID" }
        description = { en: `Value of the \`${kind}\` scope kind.` }
      } else {
        // Колонка без походження в метаданих (не трапляється для видів 1С);
        // тип відомий лише фізично.
        name = column.name
        source = { raw: column.type }
      }

      const { ts, nullable } = valueType(source, targets, paired)
      const readonly = column.generated === undefined ? "" : "readonly "
      lines.push(
        ...doc(member, title, description),
        `${member}${readonly}${fieldName(name)}: ${ts}${nullable && !column.notNull ? " | null" : ""}`
      )
    })
    return lines
  }

  const namespaces: string[] = []
  for (const def of Object.values(KIND_REGISTRY)) {
    if (def.materializes !== "table") continue
    const items: { name: string; text: string }[] = []
    for (const object of model.objects) {
      if (object.kind !== def.kind) continue
      // Основна таблиця — без `part` і без ТЧ; похідні таблиці регістрів
      // інтерфейсів не мають.
      const main = model.physical.tables.find(
        (table) =>
          table.origin.objectId === object.id &&
          table.origin.part === undefined &&
          table.origin.tabularSectionId === undefined
      )
      if (main === undefined) continue

      const data = object.data as {
        title?: LocalizedString
        description?: LocalizedString
        tabularSections?: TabularSection[]
      } & Record<string, unknown>

      const styled = (columns: readonly StandardColumnDef[]) =>
        new Map(
          columns.map((column) => [standardLogicalName(column, style), column])
        )
      const singleton = registerSingletonOf(object)
      const mainStandard = styled([
        ...(singleton === undefined ? [] : [singleton]),
        ...def.standardColumns(object.data),
      ])
      const sectionStandard = styled(
        def.tabularSectionColumns?.(object.data) ?? []
      )

      const elements = new Map<string, ElementSource>()
      const addElement = (element: ElementSource) => {
        if (element.id !== undefined) elements.set(element.id, element)
      }
      for (const field of def.columnFields) {
        for (const element of (data[field] ?? []) as ElementSource[]) {
          addElement(element)
        }
      }
      const sections =
        def.tabularSectionColumns === undefined
          ? []
          : (data.tabularSections ?? [])
      for (const section of sections) {
        for (const attribute of section.attributes) addElement(attribute)
      }

      const targetsOf = (column: StandardColumnDef) =>
        standardTargetRefs(column, object.data)
      const block = model.presentation.objects.find(
        (p) => p.objectId === object.id
      )
      const overrides = new Map(Object.entries(block?.standardAttributes ?? {}))

      const sectionNames = sections.map((section) => {
        const name = pascal(section.name)
        const path = [pascal(def.dir), object.name, name]
        return {
          section,
          name,
          alias: path.join("_"),
          target: path.join("."),
        }
      })

      const body = emitFields(
        main,
        mainStandard,
        elements,
        targetsOf,
        overrides,
        STEP.repeat(2)
      )
      // У схемі ТЧ немає `description`, тож поле-масив несе лише заголовок.
      for (const { section, alias, target } of sectionNames) {
        aliases.set(alias, target)
        body.push(
          ...doc(STEP.repeat(2), section.title, undefined),
          `${STEP.repeat(2)}${fieldName(section.name)}: ${alias}[]`
        )
      }
      const parts = [
        [
          ...doc(STEP, data.title, data.description),
          `${STEP}export interface ${object.name} {`,
          ...body,
          `${STEP}}`,
        ].join("\n"),
      ]

      // ТЧ — вкладений простір імен власника (злиття з інтерфейсом):
      // `Documents.Sale.Goods` не зіштовхується з документом `SaleGoods`.
      const rows = [...sectionNames]
        .sort((a, b) => compareStrings(a.name, b.name))
        .flatMap(({ section, name }) => {
          const table = model.physical.tables.find(
            (candidate) =>
              candidate.origin.objectId === object.id &&
              candidate.origin.tabularSectionId === section.id
          )
          if (table === undefined) return []
          const inner = STEP.repeat(2)
          return [
            [
              ...doc(inner, section.title, undefined),
              `${inner}export interface ${name} {`,
              ...emitFields(
                table,
                sectionStandard,
                elements,
                targetsOf,
                new Map(
                  Object.entries(
                    block?.sections?.find((p) => p.sectionId === section.id)
                      ?.standardAttributes ?? {}
                  )
                ),
                STEP.repeat(3)
              ),
              `${inner}}`,
            ].join("\n"),
          ]
        })
      if (rows.length > 0) {
        parts.push(
          [
            `${STEP}export namespace ${object.name} {`,
            rows.join("\n\n"),
            `${STEP}}`,
          ].join("\n")
        )
      }
      items.push({ name: object.name, text: parts.join("\n\n") })
    }
    if (items.length === 0) continue
    // Порядок за ім'ям, а не за порядком файлів: додання об'єкта не зсуває
    // сусідів, а diff згенерованого файлу лишається мінімальним.
    items.sort((a, b) => compareStrings(a.name, b.name))
    namespaces.push(
      [
        `export declare namespace ${pascal(def.dir)} {`,
        items.map((item) => item.text).join("\n\n"),
        "}",
      ].join("\n")
    )
  }
  const aliasLines = [...aliases]
    .sort(([a], [b]) => compareStrings(a, b))
    .map(([alias, target]) => `type ${alias} = ${target}`)
  return `${[
    HEADER,
    JSON_TYPE,
    ...namespaces,
    ...(aliasLines.length === 0 ? [] : [aliasLines.join("\n")]),
    // Робить псевдоніми приватними: у `.d.ts` без явного експорту все
    // оголошене на верхньому рівні вважається експортованим.
    "export {}",
  ].join("\n\n")}\n`
}

function pick(text: LocalizedString | undefined): string | undefined {
  return text?.en ?? text?.uk
}

function fieldName(name: string): string {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name)
}

/** `order_items` і `orderItems` дають однаковий PascalCase-хвіст імені. */
function pascal(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/)
    .filter((part) => part !== "")
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("")
}
