import { describe, it, expect } from "vitest"
import { generateProjectDDL } from "../generate-table"
import type { ProjectModel } from "@simetra/core"
import type { GeneratorOptions } from "@simetra/generator-api"

// Базові налаштування проєкту для всіх тестів
function baseProject(
  overrides?: Partial<ProjectModel["project"]>
): ProjectModel["project"] {
  return {
    name: "test-project",
    schemaVersion: "1.0",
    defaultLocale: "uk",
    database: {
      target: "postgresql",
      schema: "public",
    },
    generation: {
      tablePrefix: "",
      enumStrategy: "pgEnum",
      constantsStrategy: "singleTable",
    },
    ...overrides,
  }
}

function emptyProject(overrides?: Partial<ProjectModel>): ProjectModel {
  return {
    project: baseProject(),
    catalogs: [],
    documents: [],
    enumerations: [],
    informationRegisters: [],
    accumulationRegisters: [],
    constants: [],
    customTables: [],
    forms: [],
    ...overrides,
  }
}

const defaultOpts: Required<GeneratorOptions> = {
  schema: "public",
  enumStrategy: "pgEnum",
  constantsStrategy: "singleTable",
  outputMode: "singleFile",
}

// ─── Допоміжна функція для швидкого доступу до SQL ──────────
function generateSQL(
  project: ProjectModel,
  opts?: Partial<GeneratorOptions>
): string {
  const result = generateProjectDDL(project, { ...defaultOpts, ...opts })
  return result.files[0].content
}

// ─── Header ─────────────────────────────────────────────────
describe("output header", () => {
  it("includes header comment with project name and PostgreSQL target", () => {
    const sql = generateSQL(emptyProject())
    expect(sql).toContain("Generated by Simetra DDL Generator v0.0.1")
    expect(sql).toContain("Project: test-project")
    expect(sql).toContain("Target: PostgreSQL")
  })
})

// ─── Section comments ───────────────────────────────────────
describe("section comments", () => {
  it("includes section separators for TABLES and INDEXES", () => {
    const project = emptyProject({
      catalogs: [
        {
          kind: "Catalog",
          name: "Items",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
      ],
    })
    const sql = generateSQL(project)
    expect(sql).toContain("-- TABLES")
    expect(sql).toContain("============")
  })
})

// ─── Test 1: Basic Catalog ──────────────────────────────────
describe("Catalog DDL", () => {
  const project: ProjectModel = emptyProject({
    catalogs: [
      {
        kind: "Catalog",
        name: "Products",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "FoldersAndItems",
        owners: [],
        autonumber: true,
        codeUnique: true,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "sku",
            type: "String",
            length: 50,
            required: true,
            indexed: true,
            unique: true,
            defaultValue: null,
          },
          {
            name: "price",
            type: "Numeric",
            precision: 10,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [
          {
            name: "barcodes",
            standardAttributeOverrides: {},
            attributes: [
              {
                name: "barcode",
                type: "String",
                length: 13,
                required: true,
                indexed: false,
                unique: false,
                defaultValue: null,
              },
            ],
          },
        ],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates main table", () => {
    expect(sql).toContain("CREATE TABLE cat_products")
  })

  it("has comment with metadata source", () => {
    expect(sql).toContain("-- Catalog: Products")
  })

  it("includes parent_id for hierarchy", () => {
    expect(sql).toContain("parent_id uuid")
  })

  it("includes is_folder for FoldersAndItems", () => {
    expect(sql).toContain("is_folder")
  })

  it("includes code UNIQUE constraint", () => {
    expect(sql).toContain("UNIQUE (code)")
  })

  it("sku is NOT NULL and UNIQUE", () => {
    expect(sql).toContain("sku varchar(50) NOT NULL UNIQUE")
  })

  it("price has correct numeric type", () => {
    expect(sql).toContain("price numeric(10, 2)")
  })

  it("creates tabular section table", () => {
    expect(sql).toContain("CREATE TABLE cat_products_barcodes")
  })

  it("tabular section references parent", () => {
    expect(sql).toContain("parent_id uuid NOT NULL")
  })

  it("tabular section has barcode column", () => {
    expect(sql).toContain("barcode varchar(13) NOT NULL")
  })

  it("generates autonumber trigger", () => {
    expect(sql).toContain("CREATE OR REPLACE FUNCTION cat_products_autonumber()")
    expect(sql).toContain("CREATE TRIGGER trg_cat_products_autonumber")
    expect(sql).toContain("LPAD")
  })

  it("generates indexes for indexed attributes", () => {
    expect(sql).toContain("CREATE INDEX idx_cat_products_code ON cat_products (code)")
  })

  it("generates FK index for tabular section parent", () => {
    expect(sql).toContain(
      "CREATE INDEX idx_cat_products_barcodes_parent_id ON cat_products_barcodes (parent_id)"
    )
  })

  it("emits foreign keys via ALTER TABLE", () => {
    expect(sql).toContain("-- FOREIGN KEYS")
    expect(sql).toContain("ALTER TABLE cat_products_barcodes")
    expect(sql).toContain("REFERENCES cat_products(id)")
  })

  it("includes TRIGGERS section", () => {
    expect(sql).toContain("-- TRIGGERS")
  })
})

// ─── Test 2: Document with posting ──────────────────────────
describe("Document DDL", () => {
  const project: ProjectModel = emptyProject({
    documents: [
      {
        kind: "Document",
        name: "Invoice",
        numberLength: 11,
        numberType: "String",
        autonumber: true,
        numberPeriodicity: "Year",
        registerMovements: [{ kind: "AccumulationRegister", name: "Sales" }],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "total",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: true,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates document table", () => {
    expect(sql).toContain("CREATE TABLE doc_invoice")
  })

  it("has number column", () => {
    expect(sql).toContain("number varchar(11)")
  })

  it("has posted column", () => {
    expect(sql).toContain("posted boolean")
  })

  it("generates autonumber trigger with year period", () => {
    expect(sql).toContain("CREATE OR REPLACE FUNCTION doc_invoice_autonumber()")
    expect(sql).toContain("date_trunc('year', NEW.date)")
    expect(sql).toContain("LPAD")
  })

  it("has date column", () => {
    expect(sql).toContain("date timestamptz NOT NULL")
  })
})

// ─── Test 3: Enumeration (pgEnum) ───────────────────────────
describe("Enumeration pgEnum", () => {
  const project: ProjectModel = emptyProject({
    enumerations: [
      {
        kind: "Enumeration",
        name: "OrderStatus",
        values: [
          { name: "New", displayName: { uk: "Новий", en: "New" } },
          {
            name: "InProgress",
            displayName: { uk: "В роботі", en: "In Progress" },
          },
          {
            name: "Completed",
            displayName: { uk: "Завершений", en: "Completed" },
          },
        ],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates enum type", () => {
    expect(sql).toContain("CREATE TYPE enum_order_status AS ENUM")
  })

  it("includes all values", () => {
    expect(sql).toContain("'New'")
    expect(sql).toContain("'InProgress'")
    expect(sql).toContain("'Completed'")
  })

  it("includes ENUM TYPES section", () => {
    expect(sql).toContain("-- ENUM TYPES")
  })
})

// ─── Test 4: Enumeration (lookupTable) ──────────────────────
describe("Enumeration lookupTable", () => {
  const project: ProjectModel = emptyProject({
    enumerations: [
      {
        kind: "Enumeration",
        name: "OrderStatus",
        values: [
          { name: "New", displayName: { uk: "Новий", en: "New" }, order: 0 },
          {
            name: "InProgress",
            displayName: { uk: "В роботі", en: "In Progress" },
            order: 1,
          },
          {
            name: "Completed",
            displayName: { uk: "Завершений", en: "Completed" },
            order: 2,
          },
        ],
      },
    ],
  })

  const sql = generateSQL(project, { enumStrategy: "lookupTable" })

  it("creates lookup table instead of type", () => {
    expect(sql).toContain("CREATE TABLE enum_order_status")
    expect(sql).not.toContain("CREATE TYPE enum_order_status")
  })

  it("inserts initial values", () => {
    expect(sql).toContain("INSERT INTO enum_order_status")
    expect(sql).toContain("'New'")
    expect(sql).toContain("'InProgress'")
    expect(sql).toContain("'Completed'")
  })

  it("includes display_name columns", () => {
    expect(sql).toContain("display_name_uk")
    expect(sql).toContain("display_name_en")
  })
})

// ─── Test 5: InformationRegister (periodic, RecorderSubordinate) ─
describe("InformationRegister DDL", () => {
  const project: ProjectModel = emptyProject({
    documents: [
      {
        kind: "Document",
        name: "PriceChange",
        numberLength: 11,
        numberType: "String",
        autonumber: true,
        numberPeriodicity: "None",
        registerMovements: [],
        standardAttributeOverrides: {},
        attributes: [],
        tabularSections: [],
      },
    ],
    informationRegisters: [
      {
        kind: "InformationRegister",
        name: "Prices",
        periodicity: "Day",
        writeMode: "RecorderSubordinate",
        recorderTypes: [{ kind: "Document", name: "PriceChange" }],
        standardAttributeOverrides: {},
        dimensions: [
          {
            name: "product_id",
            type: "Ref",
            ref: { kind: "Catalog", name: "Products" },
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        resources: [
          {
            name: "price",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [
          {
            name: "comment",
            type: "String",
            length: 200,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates register table", () => {
    expect(sql).toContain("CREATE TABLE ir_prices")
  })

  it("has period column", () => {
    expect(sql).toContain("period timestamptz")
  })

  it("has recorder_id column", () => {
    expect(sql).toContain("recorder_id")
  })

  it("has UNIQUE constraint with period and dimensions", () => {
    expect(sql).toMatch(/UNIQUE\s*\(.*period.*product_id_id.*\)/)
  })

  it("generates slice_last view", () => {
    expect(sql).toContain("ir_prices_slice_last")
    expect(sql).toContain("DISTINCT ON")
  })

  it("includes VIEWS section", () => {
    expect(sql).toContain("-- VIEWS")
  })
})

// ─── Test 6: AccumulationRegister (Balance) ─────────────────
describe("AccumulationRegister Balance DDL", () => {
  const project: ProjectModel = emptyProject({
    accumulationRegisters: [
      {
        kind: "AccumulationRegister",
        name: "InventoryBalance",
        registerType: "Balance",
        recorderTypes: [],
        standardAttributeOverrides: {},
        dimensions: [
          {
            name: "warehouse",
            type: "String",
            length: 100,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        resources: [
          {
            name: "quantity",
            type: "Numeric",
            precision: 15,
            scale: 3,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates register table", () => {
    expect(sql).toContain("CREATE TABLE ar_inventory_balance")
  })

  it("has movement_type column with CHECK", () => {
    expect(sql).toContain("movement_type")
    expect(sql).toContain("'Receipt'")
    expect(sql).toContain("'Expense'")
  })

  it("generates balance view with CTE and window function", () => {
    expect(sql).toContain("ar_inventory_balance_balance")
    expect(sql).toContain("WITH deltas AS")
    expect(sql).toContain("quantity_delta")
    expect(sql).toContain("SUM(quantity_delta) OVER")
    expect(sql).toContain("PARTITION BY warehouse")
    expect(sql).toContain("ORDER BY period")
  })

  it("generates turnovers view", () => {
    expect(sql).toContain("ar_inventory_balance_turnovers")
  })
})

// ─── Test 6b: AccumulationRegister Balance without dimensions ─
describe("AccumulationRegister Balance without dimensions", () => {
  const project: ProjectModel = emptyProject({
    accumulationRegisters: [
      {
        kind: "AccumulationRegister",
        name: "TotalBalance",
        registerType: "Balance",
        recorderTypes: [],
        standardAttributeOverrides: {},
        dimensions: [],
        resources: [
          {
            name: "total",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("balance view uses window function without PARTITION BY", () => {
    expect(sql).toContain("ar_total_balance_balance")
    expect(sql).toContain("WITH deltas AS")
    expect(sql).toContain("total_delta")
    expect(sql).toContain("SUM(total_delta) OVER")
    expect(sql).toContain("ORDER BY period")
    expect(sql).not.toContain("PARTITION BY")
  })
})

// ─── Test 6c: AccumulationRegister Balance with multiple resources ─
describe("AccumulationRegister Balance with multiple resources", () => {
  const project: ProjectModel = emptyProject({
    accumulationRegisters: [
      {
        kind: "AccumulationRegister",
        name: "StockBalance",
        registerType: "Balance",
        recorderTypes: [],
        standardAttributeOverrides: {},
        dimensions: [
          {
            name: "warehouse",
            type: "String",
            length: 100,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        resources: [
          {
            name: "quantity",
            type: "Numeric",
            precision: 15,
            scale: 3,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
          {
            name: "amount",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("each resource has its own cumulative column", () => {
    expect(sql).toContain("quantity_delta")
    expect(sql).toContain("amount_delta")
    expect(sql).toContain("SUM(quantity_delta) OVER")
    expect(sql).toContain("SUM(amount_delta) OVER")
    expect(sql).toContain("PARTITION BY warehouse")
  })
})

// ─── Test 7: AccumulationRegister (Turnover) ────────────────
describe("AccumulationRegister Turnover DDL", () => {
  const project: ProjectModel = emptyProject({
    accumulationRegisters: [
      {
        kind: "AccumulationRegister",
        name: "Sales",
        registerType: "Turnover",
        recorderTypes: [],
        standardAttributeOverrides: {},
        dimensions: [
          {
            name: "product",
            type: "String",
            length: 100,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        resources: [
          {
            name: "amount",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("does not have movement_type column", () => {
    expect(sql).not.toContain("movement_type")
  })

  it("generates turnovers view only", () => {
    expect(sql).toContain("ar_sales_turnovers")
  })

  it("does not generate balance view", () => {
    expect(sql).not.toContain("ar_sales_balance")
  })
})

// ─── Test 8: Constant (singleTable) ────────────────────────
describe("Constant singleTable DDL", () => {
  const project: ProjectModel = emptyProject({
    constants: [
      { kind: "Constant", name: "CompanyName", valueType: "String" },
      { kind: "Constant", name: "MaxRetries", valueType: "Integer" },
      { kind: "Constant", name: "DebugMode", valueType: "Boolean" },
    ],
  })

  const sql = generateSQL(project, { constantsStrategy: "singleTable" })

  it("creates one constants table", () => {
    expect(sql).toContain("CREATE TABLE const_settings")
  })

  it("has key/value columns", () => {
    expect(sql).toContain("key varchar(100) PRIMARY KEY")
    expect(sql).toContain("value_text text")
    expect(sql).toContain("value_numeric")
    expect(sql).toContain("value_boolean")
  })

  it("does not create separate tables", () => {
    expect(sql).not.toContain("CREATE TABLE const_company_name")
    expect(sql).not.toContain("CREATE TABLE const_max_retries")
  })
})

// ─── Test 9: Constant (separateTables) ─────────────────────
describe("Constant separateTables DDL", () => {
  const project: ProjectModel = emptyProject({
    constants: [
      { kind: "Constant", name: "CompanyName", valueType: "String" },
      { kind: "Constant", name: "MaxRetries", valueType: "Integer" },
      { kind: "Constant", name: "DebugMode", valueType: "Boolean" },
    ],
  })

  const sql = generateSQL(project, { constantsStrategy: "separateTables" })

  it("creates separate table for each constant", () => {
    expect(sql).toContain("CREATE TABLE const_company_name")
    expect(sql).toContain("CREATE TABLE const_max_retries")
    expect(sql).toContain("CREATE TABLE const_debug_mode")
  })

  it("each table has singleton check", () => {
    expect(sql).toContain("CHECK (id = 1)")
  })

  it("value column matches constant type", () => {
    // CompanyName → varchar, MaxRetries → integer, DebugMode → boolean
    expect(sql).toContain("value varchar(255)")
    expect(sql).toContain("value integer")
    expect(sql).toContain("value boolean")
  })
})

// ─── Test 10: CustomTable ──────────────────────────────────
describe("CustomTable DDL", () => {
  const project: ProjectModel = emptyProject({
    customTables: [
      {
        kind: "CustomTable",
        name: "AuditLog",
        autoAddPrimaryKey: true,
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "action",
            type: "String",
            length: 50,
            required: true,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
          {
            name: "payload",
            type: "Text",
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates custom table", () => {
    expect(sql).toContain("CREATE TABLE ct_audit_log")
  })

  it("has auto-generated id column", () => {
    expect(sql).toContain("id uuid PRIMARY KEY")
  })

  it("has custom attributes", () => {
    expect(sql).toContain("action varchar(50) NOT NULL")
    expect(sql).toContain("payload text")
  })
})

// ─── Test 11: Polymorphic Ref ──────────────────────────────
describe("Polymorphic Ref DDL", () => {
  const project: ProjectModel = emptyProject({
    catalogs: [
      {
        kind: "Catalog",
        name: "Products",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [],
        tabularSections: [],
      },
      {
        kind: "Catalog",
        name: "Services",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [],
        tabularSections: [],
      },
      {
        kind: "Catalog",
        name: "Contracts",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "subject",
            type: "Ref",
            allowedTypes: [
              { kind: "Catalog", name: "Products" },
              { kind: "Catalog", name: "Services" },
            ],
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("generates _type and _id columns without NOT NULL for optional ref", () => {
    expect(sql).toContain("subject_type varchar(100)")
    expect(sql).toContain("subject_id uuid")
    expect(sql).not.toMatch(/subject_type varchar\(100\) NOT NULL/)
    expect(sql).not.toMatch(/subject_id uuid NOT NULL/)
  })

  it("generates CHECK constraint for allowed types", () => {
    expect(sql).toContain("CHECK (subject_type IN (")
    expect(sql).toContain("'Catalog.Products'")
    expect(sql).toContain("'Catalog.Services'")
  })

  it("generates index for polymorphic id", () => {
    expect(sql).toContain("idx_cat_contracts_subject_id")
  })
})

// ─── Test 12: Cross-references ─────────────────────────────
describe("Cross-references DDL", () => {
  const project: ProjectModel = emptyProject({
    catalogs: [
      {
        kind: "Catalog",
        name: "Warehouses",
        codeLength: 5,
        codeType: "String",
        descriptionLength: 100,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [],
        tabularSections: [],
      },
      {
        kind: "Catalog",
        name: "Products",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "default_warehouse",
            type: "Ref",
            ref: { kind: "Catalog", name: "Warehouses" },
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [],
      },
    ],
    documents: [
      {
        kind: "Document",
        name: "SalesOrder",
        numberLength: 11,
        numberType: "String",
        autonumber: false,
        numberPeriodicity: "None",
        registerMovements: [],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "product",
            type: "Ref",
            ref: { kind: "Catalog", name: "Products" },
            required: true,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
          {
            name: "warehouse",
            type: "Ref",
            ref: { kind: "Catalog", name: "Warehouses" },
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("Product references Warehouse", () => {
    expect(sql).toContain("default_warehouse_id uuid")
  })

  it("SalesOrder references Products", () => {
    expect(sql).toContain("product_id uuid")
  })

  it("SalesOrder references Warehouses", () => {
    expect(sql).toContain("warehouse_id uuid")
  })

  it("generates FK indexes", () => {
    expect(sql).toContain("idx_cat_products_default_warehouse_id")
    expect(sql).toContain("idx_doc_sales_order_product_id")
    expect(sql).toContain("idx_doc_sales_order_warehouse_id")
  })

  it("emits foreign keys via ALTER TABLE", () => {
    expect(sql).toContain("ALTER TABLE cat_products")
    expect(sql).toContain("REFERENCES cat_warehouses(id)")
    expect(sql).toContain("ALTER TABLE doc_sales_order")
    expect(sql).toContain("REFERENCES cat_products(id)")
  })
})

// ─── Test 13: Ref to Enumeration (pgEnum) ──────────────────
describe("Ref to Enumeration pgEnum", () => {
  const project: ProjectModel = emptyProject({
    enumerations: [
      {
        kind: "Enumeration",
        name: "ProductType",
        values: [{ name: "Goods" }, { name: "Service" }],
      },
    ],
    catalogs: [
      {
        kind: "Catalog",
        name: "Products",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "product_type",
            type: "Ref",
            ref: { kind: "Enumeration", name: "ProductType" },
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("creates enum type first", () => {
    expect(sql).toContain("CREATE TYPE enum_product_type AS ENUM")
  })

  it("uses enum type name as column type, not uuid REFERENCES", () => {
    // Колонка має використовувати тип enum, а не uuid REFERENCES
    expect(sql).toContain("product_type enum_product_type")
    expect(sql).not.toMatch(/product_type_id uuid REFERENCES/)
  })

  it("does not generate FK index for enum ref", () => {
    // Для enum-посилань _id суфікс не додається, індекс FK не потрібен
    expect(sql).not.toContain("idx_cat_products_product_type_id")
  })
})

// ─── Test: File name ────────────────────────────────────────
describe("output file", () => {
  it("uses project name as file name", () => {
    const result = generateProjectDDL(emptyProject(), defaultOpts)
    expect(result.files).toHaveLength(1)
    expect(result.files[0].path).toBe("test-project.sql")
  })
})

// ─── Polymorphic Ref required behavior ─────────────────────
describe("Polymorphic Ref required behavior", () => {
  it("polymorphic Ref + required: false → no NOT NULL", () => {
    const project: ProjectModel = emptyProject({
      catalogs: [
        {
          kind: "Catalog",
          name: "Products",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
        {
          kind: "Catalog",
          name: "Services",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
        {
          kind: "Catalog",
          name: "Orders",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [
            {
              name: "item",
              type: "Ref",
              allowedTypes: [
                { kind: "Catalog", name: "Products" },
                { kind: "Catalog", name: "Services" },
              ],
              required: false,
              indexed: false,
              unique: false,
              defaultValue: null,
            },
          ],
          tabularSections: [],
        },
      ],
    })

    const sql = generateSQL(project)
    expect(sql).toContain("item_type varchar(100)")
    expect(sql).toContain("item_id uuid")
    expect(sql).not.toMatch(/item_type varchar\(100\) NOT NULL/)
    expect(sql).not.toMatch(/item_id uuid NOT NULL/)
  })

  it("polymorphic Ref + required: true → NOT NULL on both columns", () => {
    const project: ProjectModel = emptyProject({
      catalogs: [
        {
          kind: "Catalog",
          name: "Products",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
        {
          kind: "Catalog",
          name: "Services",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
        {
          kind: "Catalog",
          name: "Orders",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [
            {
              name: "item",
              type: "Ref",
              allowedTypes: [
                { kind: "Catalog", name: "Products" },
                { kind: "Catalog", name: "Services" },
              ],
              required: true,
              indexed: false,
              unique: false,
              defaultValue: null,
            },
          ],
          tabularSections: [],
        },
      ],
    })

    const sql = generateSQL(project)
    expect(sql).toContain("item_type varchar(100) NOT NULL")
    expect(sql).toContain("item_id uuid NOT NULL")
  })
})

// ─── Single Ref required/unique in DDL ─────────────────────
describe("Single Ref required/unique in DDL", () => {
  it("required single Ref → NOT NULL in DDL", () => {
    const project: ProjectModel = emptyProject({
      catalogs: [
        {
          kind: "Catalog",
          name: "Warehouses",
          codeLength: 5,
          codeType: "String",
          descriptionLength: 100,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
        {
          kind: "Catalog",
          name: "Products",
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [
            {
              name: "default_warehouse",
              type: "Ref",
              ref: { kind: "Catalog", name: "Warehouses" },
              required: true,
              indexed: false,
              unique: false,
              defaultValue: null,
            },
          ],
          tabularSections: [],
        },
      ],
    })

    const sql = generateSQL(project)
    expect(sql).toContain(
      "default_warehouse_id uuid NOT NULL",
    )
  })
})

// ─── Test: Same name different kinds → different tables ─────
describe("Same name different kinds", () => {
  const project: ProjectModel = emptyProject({
    informationRegisters: [
      {
        kind: "InformationRegister",
        name: "Balance",
        periodicity: "NonPeriodic",
        writeMode: "Independent",
        recorderTypes: [],
        standardAttributeOverrides: {},
        dimensions: [],
        resources: [
          {
            name: "value",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [],
      },
    ],
    accumulationRegisters: [
      {
        kind: "AccumulationRegister",
        name: "Balance",
        registerType: "Turnover",
        recorderTypes: [],
        standardAttributeOverrides: {},
        dimensions: [],
        resources: [
          {
            name: "amount",
            type: "Numeric",
            precision: 15,
            scale: 2,
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        attributes: [],
      },
    ],
  })

  const sql = generateSQL(project)

  it("InformationRegister.Balance → ir_balance", () => {
    expect(sql).toContain("CREATE TABLE ir_balance")
  })

  it("AccumulationRegister.Balance → ar_balance", () => {
    expect(sql).toContain("CREATE TABLE ar_balance")
  })
})

// ─── Test: kind-prefix with project-wide tablePrefix ────────
describe("kind-prefix with tablePrefix", () => {
  const project: ProjectModel = {
    project: {
      name: "test-project",
      schemaVersion: "1.0",
      defaultLocale: "uk",
      database: { target: "postgresql", schema: "public" },
      generation: {
        tablePrefix: "erp_",
        enumStrategy: "pgEnum",
        constantsStrategy: "singleTable",
      },
    },
    catalogs: [
      {
        kind: "Catalog",
        name: "Products",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [],
        tabularSections: [],
      },
    ],
    documents: [],
    enumerations: [],
    informationRegisters: [],
    accumulationRegisters: [],
    constants: [],
    customTables: [],
    forms: [],
  }

  const sql = generateSQL(project)

  it("prepends tablePrefix before kind-prefix", () => {
    expect(sql).toContain("CREATE TABLE erp_cat_products")
  })
})

// ─── Test: lookupTable enum ref → FK via ALTER TABLE ────────
describe("lookupTable enum ref generates FK", () => {
  const project: ProjectModel = emptyProject({
    enumerations: [
      {
        kind: "Enumeration",
        name: "Status",
        values: [{ name: "Active" }, { name: "Inactive" }],
      },
    ],
    catalogs: [
      {
        kind: "Catalog",
        name: "Orders",
        codeLength: 9,
        codeType: "String",
        descriptionLength: 150,
        hierarchyType: "None",
        owners: [],
        autonumber: false,
        codeUnique: false,
        mainPresentation: "Description",
        predefinedItems: [],
        standardAttributeOverrides: {},
        attributes: [
          {
            name: "status",
            type: "Ref",
            ref: { kind: "Enumeration", name: "Status" },
            required: false,
            indexed: false,
            unique: false,
            defaultValue: null,
          },
        ],
        tabularSections: [],
      },
    ],
  })

  const sql = generateSQL(project, { enumStrategy: "lookupTable" })

  it("generates FK for lookupTable enum ref via ALTER TABLE", () => {
    expect(sql).toContain("ALTER TABLE cat_orders")
    expect(sql).toContain("REFERENCES enum_status(id)")
  })
})

// ─── Test: identifier > 63 chars → warning ─────────────────
describe("identifier length warning", () => {
  it("generates warning for identifier exceeding 63 chars", () => {
    const longName = "A".repeat(60)
    const project: ProjectModel = emptyProject({
      catalogs: [
        {
          kind: "Catalog",
          name: longName,
          codeLength: 9,
          codeType: "String",
          descriptionLength: 150,
          hierarchyType: "None",
          owners: [],
          autonumber: false,
          codeUnique: false,
          mainPresentation: "Description",
          predefinedItems: [],
          standardAttributeOverrides: {},
          attributes: [],
          tabularSections: [],
        },
      ],
    })

    const result = generateProjectDDL(project, defaultOpts)
    expect(result.warnings.length).toBeGreaterThan(0)
    expect(result.warnings.some((w) => w.includes("63"))).toBe(true)
  })
})
