import { describe, expect, it } from "vitest"
import type { PhysicalEnumType, PhysicalTable } from "simetra/model"
import {
  renderComments,
  renderEnumType,
  renderForeignKeys,
  renderIndexes,
  renderRowLevelSecurity,
  renderTable,
} from "simetra/schema"

const ORIGIN = { objectId: "00000000-0000-4000-8000-000000000001" }

function table(overrides: Partial<PhysicalTable> = {}): PhysicalTable {
  return {
    schema: "app",
    name: "items",
    origin: ORIGIN,
    rowLevelSecurity: "off",
    columns: [{ name: "id", type: "uuid", notNull: true, origin: {} }],
    uniques: [],
    checks: [],
    foreignKeys: [],
    indexes: [],
    ...overrides,
  }
}

const sql = (statements: { sql: string }[]) =>
  statements.map((s) => s.sql).join("\n")

describe("renderTable", () => {
  it("catalog table", () => {
    const result = renderTable(
      table({
        name: "currencies",
        columns: [
          { name: "id", type: "uuid", notNull: true, origin: {} },
          {
            name: "code",
            type: "text",
            notNull: true,
            collation: { name: "und-x-icu" },
            origin: {},
          },
          {
            name: "created",
            type: "timestamp with time zone",
            notNull: true,
            default: "now()",
            origin: {},
          },
          {
            name: "seq",
            type: "bigint",
            notNull: true,
            identity: {
              generation: "byDefault",
              sequence: "currencies_seq_seq",
            },
            origin: {},
          },
          {
            name: "kind",
            type: "integer",
            notNull: true,
            identity: { generation: "always", sequence: "currencies_kind_seq" },
            origin: {},
          },
        ],
        primaryKey: { name: "currencies_pkey", columns: ["id"] },
        checks: [
          { name: "currencies_code_check", expression: "length(code) > 0" },
        ],
      })
    )
    expect(result.map((s) => [s.kind, s.object])).toEqual([
      ["table", "app.currencies"],
    ])
    expect(sql(result)).toMatchInlineSnapshot(`
      "CREATE TABLE app.currencies (
        id uuid NOT NULL,
        code text COLLATE "und-x-icu" NOT NULL,
        created timestamp with time zone DEFAULT now() NOT NULL,
        seq bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME app.currencies_seq_seq) NOT NULL,
        kind integer GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME app.currencies_kind_seq) NOT NULL,
        CONSTRAINT currencies_pkey PRIMARY KEY (id),
        CONSTRAINT currencies_code_check CHECK (length(code) > 0)
      );"
    `)
  })

  it("generated number period column", () => {
    const result = renderTable(
      table({
        columns: [
          {
            name: "date",
            type: "timestamp with time zone",
            notNull: true,
            origin: {},
          },
          {
            name: "number_period",
            type: "date",
            notNull: true,
            generated: {
              expression:
                "(date_trunc('month'::text, (date AT TIME ZONE 'Europe/Kyiv'::text)))::date",
            },
            origin: {},
          },
        ],
      })
    )
    expect(sql(result)).toMatchInlineSnapshot(`
      "CREATE TABLE app.items (
        date timestamp with time zone NOT NULL,
        number_period date GENERATED ALWAYS AS ((date_trunc('month'::text, (date AT TIME ZONE 'Europe/Kyiv'::text)))::date) STORED NOT NULL
      );"
    `)
  })

  it("unique nulls not distinct and deferrable", () => {
    const result = renderTable(
      table({
        primaryKey: {
          name: "items_pkey",
          columns: ["id"],
          deferrable: "initiallyDeferred",
        },
        uniques: [
          {
            name: "items_a_b_key",
            columns: ["a", "b"],
            nullsNotDistinct: true,
            deferrable: "deferrable",
          },
          { name: "items_c_key", columns: ["c"], nullsNotDistinct: false },
        ],
      })
    )
    expect(sql(result)).toMatchInlineSnapshot(`
      "CREATE TABLE app.items (
        id uuid NOT NULL,
        CONSTRAINT items_pkey PRIMARY KEY (id) DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT items_a_b_key UNIQUE NULLS NOT DISTINCT (a, b) DEFERRABLE,
        CONSTRAINT items_c_key UNIQUE (c)
      );"
    `)
  })

  it("identifiers are quoted", () => {
    const result = renderTable(
      table({
        schema: "My Schema",
        name: "select",
        columns: [
          { name: "order", type: "text", notNull: false, origin: {} },
          { name: 'we"ird', type: "text", notNull: false, origin: {} },
        ],
        primaryKey: { name: "select_pkey", columns: ["order"] },
      })
    )
    expect(sql(result)).toMatchInlineSnapshot(`
      "CREATE TABLE "My Schema"."select" (
        "order" text,
        "we""ird" text,
        CONSTRAINT select_pkey PRIMARY KEY ("order")
      );"
    `)
  })
})

describe("determinism", () => {
  it("deterministic", () => {
    // Глибоко заморожений вхід: рендер не мутує знімок, тож повтор — той самий SQL.
    const freeze = <T>(value: T): T => {
      if (typeof value === "object" && value !== null) {
        Object.values(value).forEach(freeze)
        Object.freeze(value)
      }
      return value
    }
    const t = freeze(
      table({
        checks: [{ name: "c", expression: "true" }],
        indexes: [
          {
            name: "i",
            unique: false,
            method: "btree",
            keys: [{ column: "id" }],
            include: [],
            nullsNotDistinct: false,
          },
        ],
      })
    )
    const once = [...renderTable(t), ...renderIndexes(t)]
    expect(once).toEqual([...renderTable(t), ...renderIndexes(t)])
  })
})

describe("renderIndexes", () => {
  it("partial and expression index with order and opclass", () => {
    const result = renderIndexes(
      table({
        indexes: [
          {
            name: "items_lower_name_idx",
            unique: true,
            method: "btree",
            keys: [
              { expression: "lower(name)", order: "desc", nulls: "first" },
              {
                column: "title",
                opclass: { schema: "extensions", name: "gin_trgm_ops" },
                collation: { name: "C" },
              },
              { column: "kind", opclass: { name: "int4_ops" } },
            ],
            include: ["id", "created"],
            where: "(deleted_at IS NULL)",
            nullsNotDistinct: true,
          },
          {
            name: "items_tags_idx",
            unique: false,
            method: "gin",
            keys: [{ column: "tags" }],
            include: [],
            nullsNotDistinct: false,
          },
        ],
      })
    )
    expect(result.map((s) => [s.kind, s.object])).toEqual([
      ["index", "app.items_lower_name_idx"],
      ["index", "app.items_tags_idx"],
    ])
    expect(sql(result)).toMatchInlineSnapshot(`
      "CREATE UNIQUE INDEX items_lower_name_idx ON app.items USING btree ((lower(name)) DESC NULLS FIRST, title COLLATE "C" extensions.gin_trgm_ops, kind int4_ops) INCLUDE (id, created) NULLS NOT DISTINCT WHERE (deleted_at IS NULL);
      CREATE INDEX items_tags_idx ON app.items USING gin (tags);"
    `)
  })
})

describe("renderForeignKeys", () => {
  it("foreign key with actions", () => {
    const result = renderForeignKeys(
      table({
        foreignKeys: [
          {
            name: "items_owner_fkey",
            columns: ["owner_id"],
            references: { schema: "auth", table: "users", columns: ["id"] },
            onDelete: "setNull",
            onUpdate: "noAction",
            deferrable: "no",
          },
          {
            name: "items_parent_fkey",
            columns: ["parent_id", "kind"],
            references: {
              schema: "app",
              table: "items",
              columns: ["id", "kind"],
            },
            onDelete: "cascade",
            onUpdate: "restrict",
            deferrable: "initiallyDeferred",
          },
        ],
      })
    )
    expect(sql(result)).toMatchInlineSnapshot(`
      "ALTER TABLE app.items ADD CONSTRAINT items_owner_fkey FOREIGN KEY (owner_id) REFERENCES auth.users (id) ON DELETE SET NULL ON UPDATE NO ACTION;
      ALTER TABLE app.items ADD CONSTRAINT items_parent_fkey FOREIGN KEY (parent_id, kind) REFERENCES app.items (id, kind) ON DELETE CASCADE ON UPDATE RESTRICT DEFERRABLE INITIALLY DEFERRED;"
    `)
  })
})

describe("renderEnumType", () => {
  it("enum type keeps value order", () => {
    const type: PhysicalEnumType = {
      schema: "app",
      name: "status",
      values: ["draft", "it's done", "archived"],
      origin: ORIGIN,
    }
    expect(renderEnumType(type)).toMatchInlineSnapshot(`
      {
        "kind": "enumType",
        "object": "app.status",
        "sql": "CREATE TYPE app.status AS ENUM ('draft', 'it''s done', 'archived');",
      }
    `)
  })
})

describe("renderRowLevelSecurity", () => {
  it("rls enabled and forced", () => {
    expect(renderRowLevelSecurity(table())).toEqual([])
    expect(
      sql(renderRowLevelSecurity(table({ rowLevelSecurity: "enabled" })))
    ).toMatchInlineSnapshot(
      `"ALTER TABLE app.items ENABLE ROW LEVEL SECURITY;"`
    )
    expect(sql(renderRowLevelSecurity(table({ rowLevelSecurity: "forced" }))))
      .toMatchInlineSnapshot(`
        "ALTER TABLE app.items ENABLE ROW LEVEL SECURITY;
        ALTER TABLE app.items FORCE ROW LEVEL SECURITY;"
      `)
  })
})

describe("renderComments", () => {
  it("comments", () => {
    const result = renderComments(
      table({
        comment: "Owner's items",
        columns: [
          { name: "id", type: "uuid", notNull: true, origin: {} },
          {
            name: "note",
            type: "text",
            notNull: false,
            comment: "It's a note",
            origin: {},
          },
        ],
      })
    )
    expect(sql(result)).toMatchInlineSnapshot(`
      "COMMENT ON TABLE app.items IS 'Owner''s items';
      COMMENT ON COLUMN app.items.note IS 'It''s a note';"
    `)
    expect(renderComments(table())).toEqual([])
  })
})
